# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(968, 789)
        Form.setStyleSheet("font-family:微软雅黑;")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(140, 140, 661, 591))
        self.tabWidget.setToolTipDuration(-1)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("QTabWidget::pane{\n"
"min-width:70px;\n"
"min-height:25px;\n"
"\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"\n"
"min-width:70px;\n"
"\n"
"min-height:25px;\n"
"\n"
"color: White ;\n"
"\n"
"font:15px \"Microsoft YaHei\";\n"
"\n"
"border: 0px solid;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"QTabBar::tab:selected{\n"
"\n"
"min-width:70px;\n"
"\n"
"min-height:25px;\n"
"color: #4796f0;\n"
"\n"
"font:16px \"Microsoft YaHei\";\n"
"\n"
"border: 0px solid;\n"
"\n"
"border-bottom: 2px solid;\n"
"\n"
"border-color: #4796f0;\n"
"\n"
"}\n"
"")
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(260, 10, 81, 41))
        self.label_3.setStyleSheet("font-size: 20pt;")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(40, 70, 31, 16))
        self.label_4.setStyleSheet("font-size: 10pt;")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(210, 70, 31, 16))
        self.label_5.setStyleSheet("font-size: 10pt;")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(380, 70, 31, 16))
        self.label_6.setStyleSheet("font-size: 10pt;")
        self.label_6.setObjectName("label_6")
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(80, 70, 113, 20))
        self.lineEdit.setStyleSheet("border: none;\n"
"border-radius: 5px;\n"
"font-family: Arial;\n"
"font-size: 12px;\n"
"text-align: left;")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_2.setGeometry(QtCore.QRect(250, 70, 113, 20))
        self.lineEdit_2.setStyleSheet("border: none;\n"
"border-radius: 5px;\n"
"font-family: Arial;\n"
"font-size: 12px;\n"
"text-align: left;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(40, 100, 31, 16))
        self.label_7.setStyleSheet("font-size: 10pt;")
        self.label_7.setObjectName("label_7")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_4.setGeometry(QtCore.QRect(80, 100, 531, 20))
        self.lineEdit_4.setStyleSheet("border: none;\n"
"border-radius: 5px;\n"
"font-family: Arial;\n"
"font-size: 12px;\n"
"text-align: left;")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.tab)
        self.dateTimeEdit.setGeometry(QtCore.QRect(420, 70, 101, 22))
        self.dateTimeEdit.setAcceptDrops(False)
        self.dateTimeEdit.setReadOnly(False)
        self.dateTimeEdit.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.dateTimeEdit.setAccelerated(False)
        self.dateTimeEdit.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToPreviousValue)
        self.dateTimeEdit.setKeyboardTracking(True)
        self.dateTimeEdit.setProperty("showGroupSeparator", False)
        self.dateTimeEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2023, 1, 2), QtCore.QTime(0, 0, 0)))
        self.dateTimeEdit.setDate(QtCore.QDate(2023, 1, 2))
        self.dateTimeEdit.setCurrentSection(QtWidgets.QDateTimeEdit.YearSection)
        self.dateTimeEdit.setCalendarPopup(True)
        self.dateTimeEdit.setTimeSpec(QtCore.Qt.LocalTime)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(40, 130, 61, 16))
        self.label_8.setStyleSheet("font-size: 10pt;")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(320, 130, 31, 16))
        self.label_9.setStyleSheet("font-size: 10pt;")
        self.label_9.setObjectName("label_9")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_3.setGeometry(QtCore.QRect(360, 130, 91, 20))
        self.lineEdit_3.setStyleSheet("border: none;\n"
"border-radius: 5px;\n"
"font-family: Arial;\n"
"font-size: 12px;\n"
"text-align: left;")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setEnabled(True)
        self.pushButton.setGeometry(QtCore.QRect(110, 130, 75, 23))
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet("\n"
"background-color: ;\n"
"color: black;")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.xiaoshoudan = QtWidgets.QTableWidget(self.tab)
        self.xiaoshoudan.setGeometry(QtCore.QRect(30, 170, 591, 341))
        self.xiaoshoudan.setStyleSheet("QTableWidget {\n"
"selection-background-color: lightgray;\n"
"alternate-background-color: white;\n"
"gridline-color: silver;\n"
"}\n"
"\n"
"\n"
"QTableWidgetItem {\n"
"background-color: white;\n"
"}\n"
"\n"
"")
        self.xiaoshoudan.setLineWidth(1)
        self.xiaoshoudan.setMidLineWidth(0)
        self.xiaoshoudan.setRowCount(5)
        self.xiaoshoudan.setColumnCount(7)
        self.xiaoshoudan.setObjectName("xiaoshoudan")
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.xiaoshoudan.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        item.setFont(font)
        self.xiaoshoudan.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.xiaoshoudan.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.xiaoshoudan.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.xiaoshoudan.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.xiaoshoudan.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.xiaoshoudan.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.xiaoshoudan.setItem(0, 1, item)
        self.xiaoshoudan.horizontalHeader().setVisible(True)
        self.xiaoshoudan.horizontalHeader().setCascadingSectionResizes(False)
        self.xiaoshoudan.horizontalHeader().setHighlightSections(True)
        self.xiaoshoudan.horizontalHeader().setSortIndicatorShown(False)
        self.xiaoshoudan.horizontalHeader().setStretchLastSection(True)
        self.xiaoshoudan.verticalHeader().setVisible(False)
        self.xiaoshoudan.verticalHeader().setCascadingSectionResizes(True)
        self.xiaoshoudan.verticalHeader().setHighlightSections(True)
        self.xiaoshoudan.verticalHeader().setSortIndicatorShown(False)
        self.xiaoshoudan.verticalHeader().setStretchLastSection(False)
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setGeometry(QtCore.QRect(30, 520, 81, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab)
        self.pushButton_3.setGeometry(QtCore.QRect(140, 520, 81, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab)
        self.pushButton_4.setGeometry(QtCore.QRect(250, 520, 91, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(130, 30, 113, 20))
        self.lineEdit_5.setStyleSheet("border: none;\n"
"border-radius: 5px;\n"
"font-family: Arial;\n"
"font-size: 12px;\n"
"text-align: left;")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setGeometry(QtCore.QRect(90, 30, 31, 16))
        self.label_11.setStyleSheet("font-size: 10pt;")
        self.label_11.setObjectName("label_11")
        self.chadan = QtWidgets.QTableWidget(self.tab_2)
        self.chadan.setGeometry(QtCore.QRect(10, 70, 641, 471))
        self.chadan.setStyleSheet("QTableWidget {\n"
"selection-background-color: lightgray;\n"
"alternate-background-color: white;\n"
"gridline-color: silver;\n"
"}\n"
"\n"
"\n"
"QTableWidgetItem {\n"
"background-color: white;\n"
"}\n"
"")
        self.chadan.setLineWidth(1)
        self.chadan.setMidLineWidth(0)
        self.chadan.setRowCount(5)
        self.chadan.setColumnCount(6)
        self.chadan.setObjectName("chadan")
        item = QtWidgets.QTableWidgetItem()
        self.chadan.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.chadan.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.chadan.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.chadan.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.chadan.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.chadan.setHorizontalHeaderItem(5, item)
        self.chadan.horizontalHeader().setVisible(True)
        self.chadan.horizontalHeader().setHighlightSections(True)
        self.chadan.horizontalHeader().setSortIndicatorShown(False)
        self.chadan.horizontalHeader().setStretchLastSection(True)
        self.chadan.verticalHeader().setVisible(False)
        self.chadan.verticalHeader().setCascadingSectionResizes(True)
        self.chadan.verticalHeader().setHighlightSections(True)
        self.chadan.verticalHeader().setSortIndicatorShown(False)
        self.chadan.verticalHeader().setStretchLastSection(False)
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_5.setGeometry(QtCore.QRect(290, 20, 91, 31))
        self.pushButton_5.setObjectName("pushButton_5")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_3)
        self.tabWidget_2.setGeometry(QtCore.QRect(0, 0, 661, 561))
        self.tabWidget_2.setAutoFillBackground(False)
        self.tabWidget_2.setStyleSheet("QTabWidget::pane{\n"
"min-width:70px;\n"
"min-height:25px;\n"
"border-top: 2px solid;\n"
"\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"\n"
"min-width:70px;\n"
"\n"
"min-height:25px;\n"
"\n"
"color: gray;\n"
"\n"
"font:12px \"Microsoft YaHei\";\n"
"\n"
"border: 0px solid;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"QTabBar::tab:selected{\n"
"\n"
"min-width:70px;\n"
"\n"
"min-height:25px;\n"
"color: #4796f0;\n"
"\n"
"font:13px \"Microsoft YaHei\";\n"
"\n"
"border: 0px solid;\n"
"\n"
"border-bottom: 2px solid;\n"
"\n"
"border-color: #4796f0;\n"
"\n"
"}")
        self.tabWidget_2.setTabsClosable(False)
        self.tabWidget_2.setMovable(False)
        self.tabWidget_2.setTabBarAutoHide(False)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.label_14 = QtWidgets.QLabel(self.tab_9)
        self.label_14.setGeometry(QtCore.QRect(70, 20, 16, 16))
        self.label_14.setStyleSheet("font-size: 10pt;")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.tab_9)
        self.label_15.setGeometry(QtCore.QRect(200, 20, 16, 16))
        self.label_15.setStyleSheet("font-size: 10pt;")
        self.label_15.setObjectName("label_15")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_9)
        self.pushButton_7.setGeometry(QtCore.QRect(340, 10, 91, 31))
        self.pushButton_7.setObjectName("pushButton_7")
        self.fahuozhuanban = QtWidgets.QTableWidget(self.tab_9)
        self.fahuozhuanban.setGeometry(QtCore.QRect(10, 50, 641, 481))
        self.fahuozhuanban.setStyleSheet("QTableWidget {\n"
"selection-background-color: lightgray;\n"
"alternate-background-color: white;\n"
"gridline-color: silver;\n"
"}\n"
"\n"
"\n"
"QTableWidgetItem {\n"
"background-color: white;\n"
"}\n"
"")
        self.fahuozhuanban.setLineWidth(1)
        self.fahuozhuanban.setMidLineWidth(0)
        self.fahuozhuanban.setRowCount(5)
        self.fahuozhuanban.setColumnCount(6)
        self.fahuozhuanban.setObjectName("fahuozhuanban")
        item = QtWidgets.QTableWidgetItem()
        self.fahuozhuanban.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.fahuozhuanban.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.fahuozhuanban.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.fahuozhuanban.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.fahuozhuanban.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.fahuozhuanban.setHorizontalHeaderItem(5, item)
        self.fahuozhuanban.horizontalHeader().setVisible(True)
        self.fahuozhuanban.horizontalHeader().setHighlightSections(True)
        self.fahuozhuanban.horizontalHeader().setSortIndicatorShown(False)
        self.fahuozhuanban.horizontalHeader().setStretchLastSection(True)
        self.fahuozhuanban.verticalHeader().setVisible(False)
        self.fahuozhuanban.verticalHeader().setCascadingSectionResizes(True)
        self.fahuozhuanban.verticalHeader().setHighlightSections(True)
        self.fahuozhuanban.verticalHeader().setSortIndicatorShown(False)
        self.fahuozhuanban.verticalHeader().setStretchLastSection(False)
        self.dateTimeEdit_4 = QtWidgets.QDateTimeEdit(self.tab_9)
        self.dateTimeEdit_4.setGeometry(QtCore.QRect(90, 20, 101, 22))
        self.dateTimeEdit_4.setAcceptDrops(False)
        self.dateTimeEdit_4.setReadOnly(False)
        self.dateTimeEdit_4.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.dateTimeEdit_4.setAccelerated(False)
        self.dateTimeEdit_4.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToPreviousValue)
        self.dateTimeEdit_4.setKeyboardTracking(True)
        self.dateTimeEdit_4.setProperty("showGroupSeparator", False)
        self.dateTimeEdit_4.setDateTime(QtCore.QDateTime(QtCore.QDate(2023, 1, 2), QtCore.QTime(0, 0, 0)))
        self.dateTimeEdit_4.setDate(QtCore.QDate(2023, 1, 2))
        self.dateTimeEdit_4.setCurrentSection(QtWidgets.QDateTimeEdit.YearSection)
        self.dateTimeEdit_4.setCalendarPopup(True)
        self.dateTimeEdit_4.setTimeSpec(QtCore.Qt.LocalTime)
        self.dateTimeEdit_4.setObjectName("dateTimeEdit_4")
        self.dateTimeEdit_5 = QtWidgets.QDateTimeEdit(self.tab_9)
        self.dateTimeEdit_5.setGeometry(QtCore.QRect(220, 20, 101, 22))
        self.dateTimeEdit_5.setAcceptDrops(False)
        self.dateTimeEdit_5.setReadOnly(False)
        self.dateTimeEdit_5.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.dateTimeEdit_5.setAccelerated(False)
        self.dateTimeEdit_5.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToPreviousValue)
        self.dateTimeEdit_5.setKeyboardTracking(True)
        self.dateTimeEdit_5.setProperty("showGroupSeparator", False)
        self.dateTimeEdit_5.setDateTime(QtCore.QDateTime(QtCore.QDate(2023, 1, 2), QtCore.QTime(0, 0, 0)))
        self.dateTimeEdit_5.setDate(QtCore.QDate(2023, 1, 2))
        self.dateTimeEdit_5.setCurrentSection(QtWidgets.QDateTimeEdit.YearSection)
        self.dateTimeEdit_5.setCalendarPopup(True)
        self.dateTimeEdit_5.setTimeSpec(QtCore.Qt.LocalTime)
        self.dateTimeEdit_5.setObjectName("dateTimeEdit_5")
        self.tabWidget_2.addTab(self.tab_9, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_10)
        self.pushButton_6.setGeometry(QtCore.QRect(340, 10, 91, 31))
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_12 = QtWidgets.QLabel(self.tab_10)
        self.label_12.setGeometry(QtCore.QRect(70, 20, 16, 16))
        self.label_12.setStyleSheet("font-size: 10pt;")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.tab_10)
        self.label_13.setGeometry(QtCore.QRect(200, 20, 16, 16))
        self.label_13.setStyleSheet("font-size: 10pt;")
        self.label_13.setObjectName("label_13")
        self.dateTimeEdit_2 = QtWidgets.QDateTimeEdit(self.tab_10)
        self.dateTimeEdit_2.setGeometry(QtCore.QRect(90, 20, 101, 22))
        self.dateTimeEdit_2.setAcceptDrops(False)
        self.dateTimeEdit_2.setReadOnly(False)
        self.dateTimeEdit_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.dateTimeEdit_2.setAccelerated(False)
        self.dateTimeEdit_2.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToPreviousValue)
        self.dateTimeEdit_2.setKeyboardTracking(True)
        self.dateTimeEdit_2.setProperty("showGroupSeparator", False)
        self.dateTimeEdit_2.setDateTime(QtCore.QDateTime(QtCore.QDate(2023, 1, 2), QtCore.QTime(0, 0, 0)))
        self.dateTimeEdit_2.setDate(QtCore.QDate(2023, 1, 2))
        self.dateTimeEdit_2.setCurrentSection(QtWidgets.QDateTimeEdit.YearSection)
        self.dateTimeEdit_2.setCalendarPopup(True)
        self.dateTimeEdit_2.setTimeSpec(QtCore.Qt.LocalTime)
        self.dateTimeEdit_2.setObjectName("dateTimeEdit_2")
        self.dateTimeEdit_3 = QtWidgets.QDateTimeEdit(self.tab_10)
        self.dateTimeEdit_3.setGeometry(QtCore.QRect(220, 20, 101, 22))
        self.dateTimeEdit_3.setAcceptDrops(False)
        self.dateTimeEdit_3.setReadOnly(False)
        self.dateTimeEdit_3.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.dateTimeEdit_3.setAccelerated(False)
        self.dateTimeEdit_3.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToPreviousValue)
        self.dateTimeEdit_3.setKeyboardTracking(True)
        self.dateTimeEdit_3.setProperty("showGroupSeparator", False)
        self.dateTimeEdit_3.setDateTime(QtCore.QDateTime(QtCore.QDate(2023, 1, 2), QtCore.QTime(0, 0, 0)))
        self.dateTimeEdit_3.setDate(QtCore.QDate(2023, 1, 2))
        self.dateTimeEdit_3.setCurrentSection(QtWidgets.QDateTimeEdit.YearSection)
        self.dateTimeEdit_3.setCalendarPopup(True)
        self.dateTimeEdit_3.setTimeSpec(QtCore.Qt.LocalTime)
        self.dateTimeEdit_3.setObjectName("dateTimeEdit_3")
        self.fahuotongban = QtWidgets.QTableWidget(self.tab_10)
        self.fahuotongban.setGeometry(QtCore.QRect(10, 50, 641, 441))
        self.fahuotongban.setStyleSheet("QTableWidget {\n"
"selection-background-color: lightgray;\n"
"alternate-background-color: white;\n"
"gridline-color: silver;\n"
"}\n"
"\n"
"\n"
"QTableWidgetItem {\n"
"background-color: white;\n"
"}\n"
"")
        self.fahuotongban.setLineWidth(1)
        self.fahuotongban.setMidLineWidth(0)
        self.fahuotongban.setRowCount(5)
        self.fahuotongban.setColumnCount(6)
        self.fahuotongban.setObjectName("fahuotongban")
        item = QtWidgets.QTableWidgetItem()
        self.fahuotongban.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.fahuotongban.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.fahuotongban.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.fahuotongban.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.fahuotongban.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.fahuotongban.setHorizontalHeaderItem(5, item)
        self.fahuotongban.horizontalHeader().setVisible(True)
        self.fahuotongban.horizontalHeader().setHighlightSections(True)
        self.fahuotongban.horizontalHeader().setSortIndicatorShown(False)
        self.fahuotongban.horizontalHeader().setStretchLastSection(True)
        self.fahuotongban.verticalHeader().setVisible(False)
        self.fahuotongban.verticalHeader().setCascadingSectionResizes(True)
        self.fahuotongban.verticalHeader().setHighlightSections(True)
        self.fahuotongban.verticalHeader().setSortIndicatorShown(False)
        self.fahuotongban.verticalHeader().setStretchLastSection(False)
        self.tabWidget_2.addTab(self.tab_10, "")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.tab_4)
        self.tabWidget_3.setGeometry(QtCore.QRect(0, 0, 661, 561))
        self.tabWidget_3.setAutoFillBackground(False)
        self.tabWidget_3.setStyleSheet("QTabWidget::pane{\n"
"min-width:70px;\n"
"min-height:25px;\n"
"border-top: 2px solid;\n"
"\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"\n"
"min-width:70px;\n"
"\n"
"min-height:25px;\n"
"\n"
"color: gray;\n"
"\n"
"font:12px \"Microsoft YaHei\";\n"
"\n"
"border: 0px solid;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"QTabBar::tab:selected{\n"
"\n"
"min-width:70px;\n"
"\n"
"min-height:25px;\n"
"color: #4796f0;\n"
"\n"
"font:13px \"Microsoft YaHei\";\n"
"\n"
"border: 0px solid;\n"
"\n"
"border-bottom: 2px solid;\n"
"\n"
"border-color: #4796f0;\n"
"\n"
"}")
        self.tabWidget_3.setTabsClosable(False)
        self.tabWidget_3.setMovable(False)
        self.tabWidget_3.setTabBarAutoHide(False)
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.kucunchaxun = QtWidgets.QTableWidget(self.tab_11)
        self.kucunchaxun.setGeometry(QtCore.QRect(10, 60, 641, 461))
        self.kucunchaxun.setStyleSheet("QTableWidget {\n"
"selection-background-color: lightgray;\n"
"alternate-background-color: white;\n"
"gridline-color: silver;\n"
"}\n"
"\n"
"\n"
"QTableWidgetItem {\n"
"background-color: white;\n"
"}\n"
"")
        self.kucunchaxun.setLineWidth(1)
        self.kucunchaxun.setMidLineWidth(0)
        self.kucunchaxun.setRowCount(5)
        self.kucunchaxun.setColumnCount(6)
        self.kucunchaxun.setObjectName("kucunchaxun")
        item = QtWidgets.QTableWidgetItem()
        self.kucunchaxun.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.kucunchaxun.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.kucunchaxun.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.kucunchaxun.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.kucunchaxun.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.kucunchaxun.setHorizontalHeaderItem(5, item)
        self.kucunchaxun.horizontalHeader().setVisible(True)
        self.kucunchaxun.horizontalHeader().setHighlightSections(True)
        self.kucunchaxun.horizontalHeader().setSortIndicatorShown(False)
        self.kucunchaxun.horizontalHeader().setStretchLastSection(True)
        self.kucunchaxun.verticalHeader().setVisible(False)
        self.kucunchaxun.verticalHeader().setCascadingSectionResizes(True)
        self.kucunchaxun.verticalHeader().setHighlightSections(True)
        self.kucunchaxun.verticalHeader().setSortIndicatorShown(False)
        self.kucunchaxun.verticalHeader().setStretchLastSection(False)
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_11)
        self.pushButton_8.setGeometry(QtCore.QRect(260, 10, 91, 31))
        self.pushButton_8.setObjectName("pushButton_8")
        self.tabWidget_3.addTab(self.tab_11, "")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.shangpinluru = QtWidgets.QTableWidget(self.tab_12)
        self.shangpinluru.setGeometry(QtCore.QRect(10, 60, 641, 411))
        self.shangpinluru.setStyleSheet("QTableWidget {\n"
"selection-background-color: lightgray;\n"
"alternate-background-color: white;\n"
"gridline-color: silver;\n"
"}\n"
"\n"
"\n"
"QTableWidgetItem {\n"
"background-color: white;\n"
"}\n"
"")
        self.shangpinluru.setLineWidth(1)
        self.shangpinluru.setMidLineWidth(0)
        self.shangpinluru.setRowCount(5)
        self.shangpinluru.setColumnCount(6)
        self.shangpinluru.setObjectName("shangpinluru")
        item = QtWidgets.QTableWidgetItem()
        self.shangpinluru.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.shangpinluru.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.shangpinluru.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.shangpinluru.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.shangpinluru.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.shangpinluru.setHorizontalHeaderItem(5, item)
        self.shangpinluru.horizontalHeader().setVisible(True)
        self.shangpinluru.horizontalHeader().setHighlightSections(True)
        self.shangpinluru.horizontalHeader().setSortIndicatorShown(False)
        self.shangpinluru.horizontalHeader().setStretchLastSection(True)
        self.shangpinluru.verticalHeader().setVisible(False)
        self.shangpinluru.verticalHeader().setCascadingSectionResizes(True)
        self.shangpinluru.verticalHeader().setHighlightSections(True)
        self.shangpinluru.verticalHeader().setSortIndicatorShown(False)
        self.shangpinluru.verticalHeader().setStretchLastSection(False)
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_12)
        self.pushButton_10.setGeometry(QtCore.QRect(260, 10, 91, 31))
        self.pushButton_10.setObjectName("pushButton_10")
        self.tabWidget_3.addTab(self.tab_12, "")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.textBrowser = QtWidgets.QTextBrowser(self.tab_5)
        self.textBrowser.setGeometry(QtCore.QRect(10, 61, 641, 491))
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton_11 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_11.setGeometry(QtCore.QRect(260, 20, 75, 31))
        self.pushButton_11.setObjectName("pushButton_11")
        self.tabWidget.addTab(self.tab_5, "")
        self.btn_close = QtWidgets.QPushButton(Form)
        self.btn_close.setGeometry(QtCore.QRect(720, 90, 40, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_close.sizePolicy().hasHeightForWidth())
        self.btn_close.setSizePolicy(sizePolicy)
        self.btn_close.setMinimumSize(QtCore.QSize(20, 0))
        self.btn_close.setMaximumSize(QtCore.QSize(40, 16777215))
        self.btn_close.setStyleSheet("QPushButton {    \n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    background-color: White;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(220, 220, 220);\n"
"}\n"
"\n"
"QPushButton:pressed {    \n"
"    background-color: transparent;\n"
"}")
        self.btn_close.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/resdd/24gl-extractLeft.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_close.setIcon(icon)
        self.btn_close.setObjectName("btn_close")
        self.btn_minimize = QtWidgets.QPushButton(Form)
        self.btn_minimize.setGeometry(QtCore.QRect(660, 90, 40, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_minimize.sizePolicy().hasHeightForWidth())
        self.btn_minimize.setSizePolicy(sizePolicy)
        self.btn_minimize.setMinimumSize(QtCore.QSize(20, 0))
        self.btn_minimize.setMaximumSize(QtCore.QSize(40, 16777215))
        self.btn_minimize.setStyleSheet("QPushButton {    \n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    background-color: White;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgb(220, 220, 220);\n"
"}\n"
"\n"
"QPushButton:pressed {    \n"
"    background-color: transparent;\n"
"}")
        self.btn_minimize.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/resdd/最小化.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_minimize.setIcon(icon1)
        self.btn_minimize.setAutoDefault(False)
        self.btn_minimize.setDefault(False)
        self.btn_minimize.setObjectName("btn_minimize")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(130, 170, 681, 571))
        self.label.setStyleSheet("background-color: #3678ac;; \n"
"border-bottom-left-radius: 15px; \n"
"border-bottom-right-radius: 15px;\n"
"")
        self.label.setText("")
        self.label.setScaledContents(False)
        self.label.setWordWrap(False)
        self.label.setOpenExternalLinks(False)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(120, 70, 91, 81))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/icons/resdd/1.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(130, 70, 681, 101))
        self.label_10.setStyleSheet("background-color: rgb(20,74,116);\n"
"border-top-left-radius: 15px;\n"
"border-top-right-radius: 15px; \n"
"")
        self.label_10.setText("")
        self.label_10.setScaledContents(False)
        self.label_10.setWordWrap(False)
        self.label_10.setOpenExternalLinks(False)
        self.label_10.setObjectName("label_10")
        self.label_10.raise_()
        self.label.raise_()
        self.tabWidget.raise_()
        self.btn_close.raise_()
        self.btn_minimize.raise_()
        self.label_2.raise_()

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(1)
        self.btn_minimize.clicked.connect(Form.showMinimized) # type: ignore
        self.btn_close.clicked.connect(Form.close) # type: ignore
        self.pushButton.clicked.connect(self.xiaoshoudan.update)
        self.pushButton_2.clicked.connect(self.xiaoshoudan.insertRow)
        self.pushButton_3.clicked.connect(self.xiaoshoudan.removeRow)


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "销售单"))
        self.label_4.setText(_translate("Form", "客户："))
        self.label_5.setText(_translate("Form", "电话："))
        self.label_6.setText(_translate("Form", "日期："))
        self.lineEdit.setPlaceholderText(_translate("Form", "请输入客户名称"))
        self.lineEdit_2.setPlaceholderText(_translate("Form", "请输入客户电话"))
        self.label_7.setText(_translate("Form", "地址："))
        self.lineEdit_4.setPlaceholderText(_translate("Form", "请输入客户地址"))
        self.dateTimeEdit.setDisplayFormat(_translate("Form", "yyyy年M月d日"))
        self.label_8.setText(_translate("Form", "总计金额："))
        self.label_9.setText(_translate("Form", "业务："))
        self.lineEdit_3.setPlaceholderText(_translate("Form", "业务名称"))
        item = self.xiaoshoudan.horizontalHeaderItem(0)
        item.setText(_translate("Form", "日期"))
        item = self.xiaoshoudan.horizontalHeaderItem(1)
        item.setText(_translate("Form", "货品名称"))
        item = self.xiaoshoudan.horizontalHeaderItem(2)
        item.setText(_translate("Form", "数量"))
        item = self.xiaoshoudan.horizontalHeaderItem(3)
        item.setText(_translate("Form", "单价"))
        item = self.xiaoshoudan.horizontalHeaderItem(4)
        item.setText(_translate("Form", "优惠"))
        item = self.xiaoshoudan.horizontalHeaderItem(5)
        item.setText(_translate("Form", "金额"))
        item = self.xiaoshoudan.horizontalHeaderItem(6)
        item.setText(_translate("Form", "专/通"))
        __sortingEnabled = self.xiaoshoudan.isSortingEnabled()
        self.xiaoshoudan.setSortingEnabled(False)
        self.xiaoshoudan.setSortingEnabled(__sortingEnabled)
        self.pushButton_2.setText(_translate("Form", "添加一行"))
        self.pushButton_3.setText(_translate("Form", "删除这行"))
        self.pushButton_4.setText(_translate("Form", "提交订单"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "报单"))
        self.lineEdit_5.setPlaceholderText(_translate("Form", "请输入客户电话"))
        self.label_11.setText(_translate("Form", "电话："))
        item = self.chadan.horizontalHeaderItem(0)
        item.setText(_translate("Form", "日期"))
        item = self.chadan.horizontalHeaderItem(1)
        item.setText(_translate("Form", "货物"))
        item = self.chadan.horizontalHeaderItem(2)
        item.setText(_translate("Form", "数量"))
        item = self.chadan.horizontalHeaderItem(3)
        item.setText(_translate("Form", "单价"))
        item = self.chadan.horizontalHeaderItem(4)
        item.setText(_translate("Form", "金额"))
        item = self.chadan.horizontalHeaderItem(5)
        item.setText(_translate("Form", "优惠"))
        self.pushButton_5.setText(_translate("Form", "查询订单"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "查单"))
        self.label_14.setText(_translate("Form", "从"))
        self.label_15.setText(_translate("Form", "到"))
        self.pushButton_7.setText(_translate("Form", "查找"))
        item = self.fahuozhuanban.horizontalHeaderItem(0)
        item.setText(_translate("Form", "日期"))
        item = self.fahuozhuanban.horizontalHeaderItem(1)
        item.setText(_translate("Form", "货物"))
        item = self.fahuozhuanban.horizontalHeaderItem(2)
        item.setText(_translate("Form", "数量"))
        item = self.fahuozhuanban.horizontalHeaderItem(3)
        item.setText(_translate("Form", "单价"))
        item = self.fahuozhuanban.horizontalHeaderItem(4)
        item.setText(_translate("Form", "金额"))
        item = self.fahuozhuanban.horizontalHeaderItem(5)
        item.setText(_translate("Form", "优惠"))
        self.dateTimeEdit_4.setDisplayFormat(_translate("Form", "yyyy年M月d日"))
        self.dateTimeEdit_5.setDisplayFormat(_translate("Form", "yyyy年M月d日"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_9), _translate("Form", "专版"))
        self.pushButton_6.setText(_translate("Form", "查找"))
        self.label_12.setText(_translate("Form", "从"))
        self.label_13.setText(_translate("Form", "到"))
        self.dateTimeEdit_2.setDisplayFormat(_translate("Form", "yyyy年M月d日"))
        self.dateTimeEdit_3.setDisplayFormat(_translate("Form", "yyyy年M月d日"))
        item = self.fahuotongban.horizontalHeaderItem(0)
        item.setText(_translate("Form", "日期"))
        item = self.fahuotongban.horizontalHeaderItem(1)
        item.setText(_translate("Form", "货物"))
        item = self.fahuotongban.horizontalHeaderItem(2)
        item.setText(_translate("Form", "数量"))
        item = self.fahuotongban.horizontalHeaderItem(3)
        item.setText(_translate("Form", "单价"))
        item = self.fahuotongban.horizontalHeaderItem(4)
        item.setText(_translate("Form", "金额"))
        item = self.fahuotongban.horizontalHeaderItem(5)
        item.setText(_translate("Form", "优惠"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_10), _translate("Form", "通版"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "发货"))
        item = self.kucunchaxun.horizontalHeaderItem(0)
        item.setText(_translate("Form", "日期"))
        item = self.kucunchaxun.horizontalHeaderItem(1)
        item.setText(_translate("Form", "货物"))
        item = self.kucunchaxun.horizontalHeaderItem(2)
        item.setText(_translate("Form", "数量"))
        item = self.kucunchaxun.horizontalHeaderItem(3)
        item.setText(_translate("Form", "单价"))
        item = self.kucunchaxun.horizontalHeaderItem(4)
        item.setText(_translate("Form", "金额"))
        item = self.kucunchaxun.horizontalHeaderItem(5)
        item.setText(_translate("Form", "优惠"))
        self.pushButton_8.setText(_translate("Form", "查询全部商品"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_11), _translate("Form", "库存查询"))
        item = self.shangpinluru.horizontalHeaderItem(0)
        item.setText(_translate("Form", "日期"))
        item = self.shangpinluru.horizontalHeaderItem(1)
        item.setText(_translate("Form", "货物"))
        item = self.shangpinluru.horizontalHeaderItem(2)
        item.setText(_translate("Form", "数量"))
        item = self.shangpinluru.horizontalHeaderItem(3)
        item.setText(_translate("Form", "单价"))
        item = self.shangpinluru.horizontalHeaderItem(4)
        item.setText(_translate("Form", "金额"))
        item = self.shangpinluru.horizontalHeaderItem(5)
        item.setText(_translate("Form", "优惠"))
        self.pushButton_10.setText(_translate("Form", "确定写入商品"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_12), _translate("Form", "商品录入"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Form", "商品"))
        self.pushButton_11.setText(_translate("Form", "链接服务器"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Form", "服务器"))
        self.btn_close.setToolTip(_translate("Form", "退出"))
        self.btn_minimize.setToolTip(_translate("Form", "最小化"))
import res_rc
